### ISSUE TITLE
Don't count instructors dequeueing themselves

### ISSUE THREAD

**Issue by moosingin3space** [mterwill/office-hours-help-queue#103]

**Comment by mterwill** [comment]
The 'take all instructors offline' button is provided for this purpose. Other than opening/closing the queue which instructors are online has no bearing on the application's behavior. I'd imagine getting the UI right for this wouldn't be the easiest either.

I'd happily accept a PR for this issue but have no plans to implement it myself.

**Comment by mterwill** [comment]
Closing as won't fix, but would happily accept a PR.
