### ISSUE TITLE
Add option to enforce single queueing

### ISSUE THREAD

**Issue by marcus-darden** [mterwill/office-hours-help-queue#116]
Students will join multiple queues and arbitrage help/wait times. If balances are far enough off, they then attend two help sessions for one wait.

**Comment by mterwill** [comment]
You want to prevent students from being on multiple queues for the same course or multiple queues across all courses?

**Comment by MiloATH** [comment]
I imagine it is multiple queues for the same course. Personally, I think it is reasonable for students to be on multiple queues if they are all different courses.

**Comment by marcus-darden** [comment]
Nice!

Is that a configurable setting, or is it just universal?


Thanks,
    MMD
--
Prof. Marcus M. Darden
Lec IV, Computer Science and Engineering
2644 Beyster Building, 734.764.3643
University of Michigan
*"Electronic Mail is not secure, may not be read every day, and should not
be used for urgent or sensitive issues"*

**Comment by MiloATH** [comment]
It's universal 🌏!
