### ISSUE TITLE
Dynamic HTML title

### ISSUE THREAD

**Issue by cyanliu** [mterwill/office-hours-help-queue#131]
This is just a tiny suggestion, but I think the title of the OH site could be made more dynamic to provide slightly more information at a glance. I was specifically thinking of something depicted in the image below

![image](https://user-images.githubusercontent.com/11037821/37312234-9ad600ae-2620-11e8-82bd-f11928e56879.png)

where the `(1)` would correspond to the number of people currently on the queue. I'm an IA for EECS398 where there could potentially be long stretches of time without any queue activity, and I don't always keep the OH queue open on my browser, but I do often have the tab in whatever my active window is.

I realize that most queues don't have this problem, but I'd imagine similarly styled bite-sized pieces of information in the tab could be useful for students as well. For example, if they wanted to know their position on the queue without opening the tab, maybe it could look like the following:

![image](https://user-images.githubusercontent.com/11037821/37312270-c2bd9b9a-2620-11e8-8279-7e1bb0791fcd.png)

Thoughts?

**Comment by mterwill** [comment]
I think this is a great idea! It wouldn't be terribly difficult, either, as we have the current state of the queue in the [main react component](https://github.com/mterwill/office-hours-help-queue/blob/master/app/assets/javascripts/components/course_queue.js.jsx) and you could hook into that and set `document.title`.

FWIW the queue is supposed to notify you if a new request comes in and you're not on that tab.

https://github.com/mterwill/office-hours-help-queue/blob/cdefbf248a31266ad7c597d36218aba68adde081/app/assets/javascripts/components/course_queue.js.jsx#L34-L38

If there's an issue with that I'd love to get it fixed, too!

**Comment by cyanliu** [comment]
I admittedly didn't even realize that I had browser notifications disabled this whole time until after I made this suggestion, but yeah maybe there is some repetitive functionality happening here 😅 ...(that's definitely my bad)

But I'd imagine the queue position feature would be more feasible than creating estimated wait time...maybe...? I know that resolve timestamps are recorded, but I haven't poked around the code enough to check whether the "start" (?) time is recorded as well 😬
