### ISSUE TITLE
Allow students to display nickname

### ISSUE THREAD

**Issue by sabihb** [mterwill/office-hours-help-queue#138]
It would be great if students could display (perhaps next to their name in parenthesis) the name they would like called out when you're trying to find them in Office Hours. It's a small thing, but I think it would help OH go a little bit more smoothly, and I actually have a few students that currently use the description for this. And hopefully students wouldn't misuse the feature by making us call them silly names (but who knows).

Thank you!

**Comment by mterwill** [comment]
This is a great idea and straightforward to implement. Thanks for mentioning it!

**Comment by mterwill** [comment]
Deployed! Users can now update their nickname on the 'Settings' page linked from the bottom of the main course list page. If a user has set a nickname, it will be displayed in parentheses next to their official name on the queue.

**Comment by sabihb** [comment]
Awesome! Thank you so much for your quick work on this!
