### ISSUE TITLE
Clicking request does nothing - This is a bug

### ISSUE THREAD

**Issue by wesleytian** [mterwill/office-hours-help-queue#140]
I'm having this persistent issue on all devices and all browsers including mobile where clicking request does nothing. 

The button physically responds, but I am not added to the queue.

This also happens on other queues such as EECS 498, the 2 credit bonus section for EECS 482 OS

**Comment by mterwill** [comment]
Hey @wesleytian, do you see any errors in your browser's console?

**Comment by mterwill** [comment]
It looks like you have an open request from 12 days ago in an EECS 482 queue [here](https://oh.eecs.umich.edu/course_queues/387). There is a limit of one open request per user per course. Please cancel that request and let me know if you still have an issue.

**Comment by wesleytian** [comment]
Yup, that did it. Thanks!
