### ISSUE TITLE
Private mode considers groups

### ISSUE THREAD

**Issue by pgossman** [mterwill/office-hours-help-queue#163]
Thank you very much for #161, it has been very nice to have this. However, it would be great if the location and description were not hidden from other group members. Now that we are always doing OH virtually, having to ask our group member to send the Hangouts link in some other chat, or have them verify the location is even set, causes a bit of a headache.

**Comment by mterwill** [comment]
🤦‍♂ I completely forgot about course groups. Thanks for mentioning! Will get a PR up shortly.
