### ISSUE TITLE
Course queues loading for 20+ minutes for some students

### ISSUE THREAD

**Issue by tabaddor** [mterwill/office-hours-help-queue#174]
It seems as if for some students, myself included, when clicking on the queue for a specific course (for example, EECS 388), I am met with a loading screen for 20-30+ minutes. Below is a screenshot:

![Capture](https://user-images.githubusercontent.com/44756122/92489868-4318cb00-f1be-11ea-9339-ddb89c720bc6.PNG)

Interestingly, not every course results in this error. For some (EECS 270, for example), I can sign up for the queue immediately as expected.

**Comment by KhidirA** [comment]
same for eecs 281

**Comment by oalejel** [comment]
please resolve this soon!

**Comment by mterwill** [comment]
Could you please post a screenshot of your browser console?

**Comment by oalejel** [comment]
> Could you please post a screenshot of your browser console?

I'm a teaching assistant, so I can only try to display the loading behavior being described by students with OH for classes that I'm not enrolled for. Here's EECS 482's queue, with unending loading indicators:
<img width="1792" alt="Screen Shot 2020-09-08 at 1 02 05 PM" src="https://user-images.githubusercontent.com/6698326/92506501-8fbad100-f1d3-11ea-8a72-ea7c53c69341.png">

**Comment by michaeljecmen** [comment]
I poked around for quite some time, here's what I've found:
- queue can be loaded when there's no one in it, but when there is one or more student in the queue it it loads endlessly like in the picture
- happens consistently for other courses too (ones I'm not registered for this semester, ones I'm taking currently, and eecs 281 for which I am an IA)
- could have to do with me being a late hire (some uniqname issue? not sure if those are even checked in oh queues)
- suspicious X-XSS-Protection: 1; mode=block tag in dev console for element associated with other student in queue when I try to inspect element (I'll try to recreate this asap)
- does not work even with a fresh install of chrome, chromium, or firefox and minimal security settings, doubt it's a browser issue

**Comment by tabaddor** [comment]
>     * queue can be loaded when there's no one in it, but when there is one or more student in the queue it it loads endlessly like in the picture

I've loaded a queue (EECS 270) immediately when there were multiple students on the queue.

**Comment by mterwill** [comment]
I can't reproduce locally but the "undefined is not an object" on `this.props.location.trim()` is a relatively recent addition, in https://github.com/mterwill/office-hours-help-queue/pull/173/files. Will revert that for now.

**Comment by mterwill** [comment]
Revert is deployed.

**Comment by mterwill** [comment]
Ah - looks like this only happens in private mode, where we don't include a location for other students' requests:

https://github.com/mterwill/office-hours-help-queue/blob/36734df33c1dee84be9cdcf68f49168a3a364db3/app/helpers/course_queues_helper.rb#L30

**Comment by michaeljecmen** [comment]
Reverted version works! Thanks.
