### ISSUE TITLE
Heroku Deployment Assets Loading

### ISSUE THREAD

**Issue by neiljohari** [mterwill/office-hours-help-queue#178]
Hi! I'm trying to deploy a mini OH queue for my 280 Lab section on Heroku. I fixed a few things to make it work on Heroku like the Procfile + ClearDB support + using REDIS via an environment var.

Right now it seems like certain assets (icons) aren't loading properly even with local asset precompilation.

Here's where I've deployed it: https://eecs-courses-oh.herokuapp.com/

Would be helpful if you had any insights? 

It seems like putting semantic UI into `vendor/assets` is the right way to go and including it from `application.css` is allowed, so I'm not really sure what's going on.

**Comment by neiljohari** [comment]
As a side question, is there any interest in a PR for easy heroku deployment? I saw an earlier issue from a few years ago that was closed due to inactivity. It would involve patching the Procfile though

**Comment by mterwill** [comment]
👋 I had tried to deploy this to Heroku a while back and ended up moving everything to `public/themes` and manually updating the minified css file. The asset build in this repo leaves much to be desired...

Maybe try [this patch](https://gist.githubusercontent.com/mterwill/dfd9da2755916e5df9288b5ee9f71c88/raw/b758609dc076e8e27310697faa27c5526e926588/asdf.patch) which you can apply with:

```
git apply <(curl https://gist.githubusercontent.com/mterwill/dfd9da2755916e5df9288b5ee9f71c88/raw/b758609dc076e8e27310697faa27c5526e926588/asdf.patch)
```

No promises 😛 - let me know if that works for you.


Re: committing back Heroku deployment - there's some cruft in here that tightly couples this repo to UMich's deployment. I'd eventually like to pull that out and make this repo completely agnostic to deployment/configuration. Would be happy to include a link out in the README/wiki though!

Also - happy to create any queues you need on https://oh.eecs.umich.edu, just let me know.

**Comment by neiljohari** [comment]
@mterwill That patch worked out perfectly :)

And that's super fair, doing that kind of refactor might even be worth upgrading to Rails 6 + Webpacker and their way of handling a React app. I might give that a try at some point in the future!

I'll definitely email you if it turns out to be more useful for me to run a queue on oh.eecs! Thanks for everything, great repo
