### ISSUE TITLE
Ping opens too many message windows

### ISSUE THREAD

**Issue by mbwangfpdc** [mterwill/office-hours-help-queue#191]
When I click the "ping" button, it opens a dialogue to add a message to my ping (good work, BTW @annieli555 , this is going to be really useful!). However, there's a bug which causes "ping" to open a dialogue window for each student in the queue. For example, if there are 4 students in the queue and I press "ping", it opens 4 dialogue windows (I have to x out 4 windows to get back to the normal queue screen). I don't know which student sees the result of which ping dialogue.

**Comment by bkayes** [comment]
I'm noticing the same issue.

**Comment by mterwill** [comment]
I'll revert for now. @annieli555 / @pl98, do you have time to look into this? Thanks!

**Comment by pl98** [comment]
@mterwill We can take a look at this issue this week.
