### ISSUE TITLE
Increase length of location field a little bit

### ISSUE THREAD

**Issue by cyrus-** [mterwill/office-hours-help-queue#206]
We ask students to put Meet / Zoom links in the location field for virtual office hours, but the length limit for that field is short enough that if they copy the auto-generated message from Meet "To join the video meeting...", it gets cut off and the URL isn't available to the staff. It would be nice to increase the length a bit to avoid this issue.

**Comment by RamchandraApte** [comment]
Yes, I'm also having the same issue. Perhaps we could expand the text when the user clicks on it.

**Comment by cyrus-** [comment]
We found a workaround for now: the full message is available in the underlying DOM, so the staff member can get at it using "Inspect Element" in your browser.
