### ISSUE TITLE
Student is not enrolled in class and can still enter queue

### ISSUE THREAD

**Issue by peterkaplan** [mterwill/office-hours-help-queue#78]
Is it possible to check if a student is in a class before allowing them to be added to the queue

**Comment by mterwill** [comment]
Has this been a recurring problem? If you (or anyone else) is on staff for a course that'd use this feature I'd be interested to hear pros/cons.

I can think of a couple of cases, e.g. a student on the waitlist, a student who late added the course, where imho this would do more harm than good. 

Implications aside, the simplest way I can think of to implement this would probably be some variant of the [groups](https://github.com/mterwill/classroom-help-queue/pull/76) functionality. That'd require instructors to keep their course roster up to date by hand. I'm hesitant towards any tightly coupled integration with Canvas or Wolverine Access, but would be open to discussion.

**Comment by peterkaplan** [comment]
The reason I bring this up is with the group feature it would be possible to have students have their friends not in the class sign up and claim to be them to get around the 1 person per group limit. 

Although students would have to be knowingly not following the rules so maybe this is not necessary.

**Comment by pmchen** [comment]
We would use this feature in EECS 482.  We have extra office hours for the students who are in the 2-credit extension (EECS 498-002), and we'd like the web site to restrict signups for that queue to those students.  I would get around the issues you raised re: class lists (e.g. students on the wait list) by having a manually-entered list, similar to how it's done for the lecture recordings.
